name = "myed-file-upload"
main = "index.ts"
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2025-10-01"




# Configure bundling to handle path aliases
[build]
command = ""
watch_dir = "../.."

# Uncomment and configure when ready to deploy
# account_id = "your-cloudflare-account-id"
# route = { pattern = "your-worker-domain.workers.dev", zone_name = "your-domain.com" }

