name = "myed-file-upload"
main = "index.ts"
compatibility_flags = [ "nodejs_compat" ,"nodejs_compat_populate_process_env"]
compatibility_date = "2025-10-01"


# Configure bundling to handle path aliases
[build]
command = "exit 0"


# Uncomment and configure when ready to deploy
# account_id = "your-cloudflare-account-id"
# route = { pattern = "your-worker-domain.workers.dev", zone_name = "your-domain.com" }

