name: Deploy Cloudflare Worker

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - workers/myed-file-upload/**
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
      - name: Pull .env from Vercel
        run: npx vercel env pull .env --token ${{ secrets.VERCEL_TOKEN }} --environment production --yes
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

      - name: Append .env to wrangler.toml
        run: |
          echo '[vars]' >> workers/myed-file-upload/wrangler.toml
          cat .env >> workers/myed-file-upload/wrangler.toml
      - name: Create temporary .npmrc and install dependencies
        run: |
          node --env-file=.env utils/generate-npmrc.js
      - name: Install root dependencies
        run: npm install
        env:
          SKIP_POSTINSTALL: true
      - name: Manually install wrangler (bug in action)
        run: |
          npm install -g wrangler@4.49.0
      - name: Deploy Worker
        run: npx wrangler deploy
        working-directory: workers/myed-file-upload
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_WORKER_API_KEY }}
